version: "3.9"
services:
  db:
    image: postgres:16
    container_name: plan-accion-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plan_accion
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d plan_accion"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: plan-accion-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/plan_accion
      JWT_SECRET: supersecreto
      JWT_EXPIRE_HOURS: "8"
      CORS_ORIGINS: http://localhost:5173
    ports:
      - "8000:8000"
